### PR TITLE
Updated routes

### LINKED ISSUE #63: Routes
Updates to the routes.

NB
- PR for this should be to `feature/update-routes` branch.

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #63

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Approved

**Comment by SkaeX** [comment]
How about disable `User`?

**Comment by BrainMaestro** [comment]
It's an update

**Comment by SkaeX** [comment]
Approved.

**Comment by SkaeX** [comment]
I'll leave the branch.

**Comment by BrainMaestro** [comment]
What for

**Pull request merged**
