### PR TITLE
Build fix

### PR DESCRIPTION
**Pull request by SkaeX**
- Attempt 1 to fix build.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
I restarted the build and it seems to work. But why?

**Comment by SkaeX** [comment]
Why what?

On Friday, 3 June 2016, BrainMaestro <notifications@github.com> wrote:

> I restarted the build and it seems to work. But why?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BrainMaestro/FCE/pull/169#issuecomment-223543985>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJghIATU0Wf4eIWE22f_ScSh7wKCJbWkks5qH__FgaJpZM4ItWYm>
> .
>


-- 
Regards,
Abdulmajid Hamza,
+234 (0) 81007608034.
Twitter: @D_Skampa

**Comment by BrainMaestro** [comment]
Why does removing `admin` fix the build

**Comment by SkaeX** [comment]
Something was fishy with the display_name for admin in the Role factory

On Friday, 3 June 2016, BrainMaestro <notifications@github.com> wrote:

> Why does removing admin fix the build
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BrainMaestro/FCE/pull/169#issuecomment-223544803>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJghIFxXgAUe1yp9LAkXnV2rUHl0Yth2ks5qIADWgaJpZM4ItWYm>
> .
>


-- 
Regards,
Abdulmajid Hamza,
+234 (0) 81007608034.
Twitter: @D_Skampa

**Comment by BrainMaestro** [comment]
Can you find the actual issue instead of removing it?

**Comment by SkaeX** [comment]
Okay Sir

On Friday, 3 June 2016, BrainMaestro <notifications@github.com> wrote:

> Can you find the actual issue instead of removing it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BrainMaestro/FCE/pull/169#issuecomment-223545683>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJghIFJQNrNvLrU48P9acfbyB1sYIQ9eks5qIAH5gaJpZM4ItWYm>
> .
>


-- 
Regards,
Abdulmajid Hamza,
+234 (0) 81007608034.
Twitter: @D_Skampa

**Comment by BrainMaestro** [comment]
Approved

**Pull request merged**
