### PR TITLE
Added current semester field to track the current semester. Fixed #5

### LINKED ISSUE #5: Add current semester column to semester table
Value of column should be a boolean

### PR DESCRIPTION
**Pull request by BrainMaestro**

### CODE REVIEW

**Comment by tenorz007** [comment]
We need to put question type mid or final in the question set table

**Comment by BrainMaestro** [comment]
The question type is in the pivot table between question set and semester. That way, a single question set can be used for different types of evaluation if necessary.

**Comment by tenorz007** [comment]
As you know, there are complications with retrieving things on that table and the type would need to be known.

**Comment by BrainMaestro** [comment]
No, there won't be a problem in that case

**Comment by tenorz007** [comment]
I know that and it may as well be put in the question set itself since it
is unique. Because it would be needed and we know we can't access the pivot.

**Pull request merged**
