### PR TITLE
Simplify query string format

### PR DESCRIPTION
**Pull request by BrainMaestro**
Uses `query=season:summer|year:2015` instead of `query=season:=summer|year:=2015`. Similar to the way laravel validation rule strings work.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Approved

**Comment by BrainMaestro** [comment]
What's up with this

**Comment by tenorz007** [comment]
It's not urgent, I haven't verified what I needed to yet. Handled the other
ones.

**Comment by tenorz007** [comment]
Approved

**Pull request merged**
