### PR TITLE
Feature repository test and method

### PR DESCRIPTION
**Pull request by tenorz007**
I wrote some of the methods along with test that I could, most of them I require data in DB to test them but the model factory doesn't help alot. 

You need to setup the TestCase class to run the factory and set in up in a way that the foreign keys and relationships are added accordingly. 

I couldn't move forward with some of the methods because of that reason.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
I want to work on #21 which will cause a lot of changes to what you've already done. After it's done and merged, we can come back and include these changes

**Comment by tenorz007** [comment]
I have been working on it long before you started whatever you are doing,
mine would be merged first then you make your changes on my own.

**Comment by BrainMaestro** [comment]
I understand that. It's just that there might be a lot of change that there's almost no point merging and then removing a lot of the code again.

**Comment by tenorz007** [comment]
I see no changes or updates in FCE @BrainMaestro

**Comment by BrainMaestro** [comment]
Laptop issues

**Comment by BrainMaestro** [comment]
We've moved on from this so I'll close this now

**Pull request closed without merging**
