### PR TITLE
Feature get question set

### PR DESCRIPTION
**Pull request by tenorz007**

### CODE REVIEW

**Comment by tenorz007** [comment]
Approved

**Comment by BrainMaestro** [comment]
Look at the change I added. It makes sense right? Also has the benefit of not showing the keys if they don't have values

**Comment by tenorz007** [comment]
I didn't do that on purpose.

**Comment by BrainMaestro** [comment]
Approved

**Comment by BrainMaestro** [comment]
You removed the commit?

**Comment by tenorz007** [comment]
You undid it?

**Comment by BrainMaestro** [comment]
No I didn't

**Pull request merged**
