### PR TITLE
Enabled sorting and link preservation

### PR DESCRIPTION
**Pull request by tenorz007**
#87 
#153

### CODE REVIEW

**Comment by tenorz007** [comment]
@SkaeX @BrainMaestro Tests are failing because of the artisan command in the permission check. They are not being rolled back after the test so it affects the database.

**Comment by BrainMaestro** [comment]
You know how to fix it?

**Comment by tenorz007** [comment]
@SkaeX that artisan command is causing failures in tests, we need to ensure it is run only in tat test once and have the changes reversed after the test.

**Comment by tenorz007** [comment]
@SkaeX So why is this still pending merge! 😠

**Comment by SkaeX** [comment]
Sorry @tenorz007, I wasn't sure why the build passed.

**Comment by SkaeX** [comment]
I've given up. I seriously don't know what is wrong. There seems to be a problem with the order data come out. cc @tenorz007

**Comment by tenorz007** [comment]
Order data like how.

**Comment by SkaeX** [comment]
@tenorz007, as in below, The data in the db is same but comes out in a some different order.

NB.
This problem affects the `get` methods in the repositories.

```
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (
-        'id' => 35
-        'crn' => 4144854
-        'course_code' => 'nostrum'
-        'semester_id' => 35
-        'school_id' => 47
-        'course_title' => 'Velit et omnis aspernatur voluptatum excepturi cupiditate.'
-        'class_time' => '23:18:38'
-        'location' => 'Nobis et quia deserunt voluptatibus et modi ut laudantium.'
-        'status' => 'locked'
-        'enrolled' => 7
-        'users' => Array (...)
-    )
-    1 => Array (
@@ @@
     )
-    2 => Array (
+    1 => Array (
@@ @@
     )
-    3 => Array (
+    2 => Array (
@@ @@
     )
-    4 => Array (
+    3 => Array (
@@ @@
         'enrolled' => 9
+        'users' => Array (...)
+    )
+    4 => Array (
+        'id' => 35
+        'crn' => 4144854
+        'course_code' => 'nostrum'
+        'semester_id' => 35
+        'school_id' => 47
+        'course_title' => 'Velit et omnis aspernatur voluptatum excepturi cupiditate.'
+        'class_time' => '23:18:38'
+        'location' => 'Nobis et quia deserunt voluptatibus et modi ut laudantium.'
+        'status' => 'locked'
+        'enrolled' => 7
         'users' => Array (...)
     )
 )
```

**Comment by SkaeX** [comment]
@tenorz007 what do we do about this? I think I can safely say your code has some bugs. Please reply.

**Comment by tenorz007** [comment]
Well you can look at what I've done, and you tell me. I barely changed
anything as far as I remember.

**Comment by SkaeX** [comment]
@tenorz007, I've fixed the bug that breaks the build on `develop` branch. The bug on your branch has nothing to do with the `develop` branch (I've rebased your branch). I want to know if you're willing to look at your code again. Please reply.

**Comment by tenorz007** [comment]
@SkaeX I actually didn't really pay attention to the dumb you showed, it possibly has to do with the fact that there is now a sort order, so the way the model factory creates it is not necessarily the same order it would be returned because of the order by parameter.

**Comment by SkaeX** [comment]
@tenorz007, I suspect so. Will you fix it so I'll merge this?

**Comment by tenorz007** [comment]
@SkaeX The quickest fix would be to remove the default sort, and order. I can't at the moment, I will look into it when today!

**Comment by tenorz007** [comment]
@SkaeX Build passed!

**Pull request merged**
