### PR TITLE
Add school controller

### PR DESCRIPTION
**Pull request by SkaeX**
Part of #62.

- Adds implementation of school controller
- Creates request
- Updates route
- Creates controller test.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
If the create and update request classes have the same rules, we can just reuse them

**Comment by BrainMaestro** [comment]
Approved. Waiting for your approval

**Comment by SkaeX** [comment]
Sorry. Approved!

**Comment by BrainMaestro** [comment]
Hmm. I think `Approved` has to be at the beginning of the comment. I'll expand it later to use a regex.

**Pull request merged**
