### PR TITLE
Added relationship between Evaluation and Question

### LINKED ISSUE #3: Add relationship from evaluation to QuestionSet and Question
This affects migrations, transformers and the model

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #3. Relationship between Evaluation and QuestionSet will be through the semester.

### CODE REVIEW

**Comment by SkaeX** [comment]
Evaluation belongs to a Question? Why please?

**Comment by tenorz007** [comment]
It's because of the way it works now. Each evaluation row will be made of a
question pertaining to that particular evaluation section.

**Comment by tenorz007** [comment]
Each evaluation row is made up of a question, yes!

**Comment by SkaeX** [comment]
Alright Sir!

**Comment by BrainMaestro** [comment]
I think we might need to use a model for the question_question_set pivot table like we were considering earlier. It would be much cleaner in my opinion

**Comment by tenorz007** [comment]
I would prefer us to use the pivot, I did tell you to make use of that pivot model as I had told you

**Comment by BrainMaestro** [comment]
Since you know about it or have at least encountered it before, why haven't you implemented it?

**Pull request merged**
