### PR TITLE
Add url string support for paging

### PR DESCRIPTION
**Pull request by BrainMaestro**
Allows urls like `/api/user?page=3` to go to the correct page.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Approved

**Comment by tenorz007** [comment]
Isn't the user already allowed to pass the page

**Comment by BrainMaestro** [comment]
Yeah but it was being ignored before. If you look at the repository functions get, there's no way to specify the page.


Sent from Outlook Mobile






On Fri, Mar 4, 2016 at 12:23 PM -0800, "tenorz007" <notifications@github.com> wrote:





Isn't the user already allowed to pass the page

---

**Comment by tenorz007** [comment]
But the repository function should have the parameter for it

**Comment by BrainMaestro** [comment]
The issue is putting it in every single get function. Not a good idea.


Sent from Outlook Mobile






On Fri, Mar 4, 2016 at 1:32 PM -0800, "tenorz007" <notifications@github.com> wrote:





But the repository function should have the parameter for it

---

**Comment by tenorz007** [comment]
Not a good idea why

**Comment by BrainMaestro** [comment]
Duplication.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 7:08 AM -0800, "tenorz007" <notifications@github.com> wrote:





Not a good idea why

---

**Comment by tenorz007** [comment]
Limit you aren't parsing...so how then would it work

**Comment by BrainMaestro** [comment]
What? Not sure what you're saying.

 I tested it with postman and it works.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 8:21 AM -0800, "tenorz007" <notifications@github.com> wrote:





Limit you aren't parsing...so how then would it work

---

**Comment by BrainMaestro** [comment]
Again, you're slowing me down. What's the issue with this one. This is a straightforward thing that shouldn't take time.

**Comment by tenorz007** [comment]
I have no problem with this one I get what you've done, it's just what
happens when you want to pass limit, you'll now do what?

**Comment by tenorz007** [comment]
Approved!

**Comment by BrainMaestro** [comment]
Look at the update I made. Passing limit wouldn't have affected it before.


Sent from Outlook Mobile






On Sun, Mar 6, 2016 at 6:17 AM -0800, "tenorz007" <notifications@github.com> wrote:





I have no problem with this one I get what you've done, it's just what
happens when you want to pass limit, you'll now do what?
On Mar 6, 2016 00:28, "BrainMaestro" <notifications@github.com> wrote:

> Again, you're slowing me down. What's the issue with this one. This is a
> straightforward thing that shouldn't take time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrainMaestro/FCE/pull/69#issuecomment-192758819>.
>


---

**Pull request merged**
