### PR TITLE
Merge multiple request files

### PR DESCRIPTION
**Pull request by SkaeX**
Takes care of #102. Also part of #62.

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Sorry it took so long. Look at the changes I made. What do you think?

Also, you need to add comments to the decision branches in the requests so it'll be easy to tell which route that set of rules belongs to. Because right now, I'd have to go and check the routes file to be sure.
Maybe add just simple `// Update` or something. When you're done, I'll squash everything back to the initial 3 commits and merge.

**Comment by SkaeX** [comment]
Approved. Would have been nice to have a pseudo standard within the request files. As it is now, some request files check `request->path()`, while some check `request->method()`. I'll suggest we do both in all the files.

**Comment by BrainMaestro** [comment]
Yeah I understand the thought process behind that. But there was one particular situation where having both added an unnecessary check. That's why I removed it. I think it back is fine


Sent from Outlook Mobile






On Sat, Mar 26, 2016 at 2:32 PM -0700, "SkaeX" <notifications@github.com> wrote:





Approved. Would have been nice to have a pseudo standard within the request files. As it is now, some request files check `request->path()`, while some check `request->method()`. I'll suggest we do both in all the files.

---

**Comment by BrainMaestro** [comment]
Is the consistency really important? I don't like checking for something that could be avoided

**Comment by SkaeX** [comment]
I'll say not as much for `V_1`. We might raise the bar later.

**Pull request merged**
