### PR TITLE
Feature add repository all exception

### PR DESCRIPTION
**Pull request by tenorz007**
PS: Additional tests may be needed to cover the exception in the controller and repository

### CODE REVIEW

**Comment by BrainMaestro** [comment]
I don't see any tests for this. Pull my change before you add it.

**Comment by tenorz007** [comment]
Did you even look at my comment......

**Comment by BrainMaestro** [comment]
Yeah well add the tests

**Comment by tenorz007** [comment]
Approved

**Comment by BrainMaestro** [comment]
Approved

**Pull request merged**
