### PR TITLE
Add search component

### PR DESCRIPTION
**Pull request by BrainMaestro**

### CODE REVIEW

**Comment by SkaeX** [comment]
The search bar would be better in the `navbar` I think. What do you think @BrainMaestro?

**Comment by BrainMaestro** [comment]
Well not every page needs a search bar. And it has extra elements unique to the page, so I'm not sure that'll work.

**Comment by SkaeX** [comment]
Nice job! However, in my opinion, I think we can do better. Check [this library](https://www.datatables.net/) out. @BrainMaestro

**Comment by BrainMaestro** [comment]
Yeah. That seems to be a front-end search however. Our search is powered by the api so it can't be that responsive.

**Comment by BrainMaestro** [comment]
Now clicking search when the no values are specified will return you to the initial table.

**Pull request merged**
