### PR TITLE
Exclude questionset questions

### PR DESCRIPTION
**Pull request by BrainMaestro**
Cleaner library supported way of excluding questions when getting a semester's question sets. 

Also noticed the hypenated `question-sets` route were not working when testing. Had to switch to underscores `question_sets`.

### CODE REVIEW

**Comment by tenorz007** [comment]
What's the advantage to this?

**Comment by BrainMaestro** [comment]
Using an in-built library supported way of achieving the same thing. 


Also because, questions are actually default includes. This makes that clearer. We might also plan on excluding something else in the future and this allows that.

**Comment by BrainMaestro** [comment]
An update would be nice. Everything is starting to take too long.

**Comment by tenorz007** [comment]
Approved

**Pull request merged**
