### PR TITLE
Feature url query search

### PR DESCRIPTION
**Pull request by tenorz007**

### CODE REVIEW

**Comment by tenorz007** [comment]
Search model by parameters #59

**Comment by BrainMaestro** [comment]
A better way of doing this would have been to create a new `search` function in the base repository that handled the searching instead of adding it to the `all` function.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 1:35 AM -0800, "tenorz007" <notifications@github.com> wrote:





Assigned #71 to @BrainMaestro.

---
Reply to this email directly or view it on GitHub:
https://github.com/BrainMaestro/FCE/pull/71#event-578740378

**Comment by tenorz007** [comment]
I disagree.

**Comment by tenorz007** [comment]
Approved!

**Comment by BrainMaestro** [comment]
Well what are your reasons?

The all function is supposed to have just one purpose. Also, having to pass null for the query when you don't need it is not a good implementation.


Remember, single responsibility.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 6:42 AM -0800, "tenorz007" <notifications@github.com> wrote:





I disagree.

---

**Comment by tenorz007** [comment]
I don't see the use of duplicating the code, when they are both doing the same thing. The responsibility of the method still stands

**Comment by BrainMaestro** [comment]
It's not duplicating. It's something completely different. This change you made affected many different methods which isn't necessary. Also, from the controllers, we'll have to include a lot of checks.


The way I want to implement it is to use a search endpoint and a search controller. That way we can add search functionality to any model without having to make changes to the repositories.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 7:49 AM -0800, "tenorz007" <notifications@github.com> wrote:





I don't see the use of duplicating the code, when they are both doing the same thing. The responsibility of the method still stands

---

**Comment by tenorz007** [comment]
Checks in the controller for what, cause I even noticed all those parameters you put cannot even be passed to the function.

**Comment by BrainMaestro** [comment]
Checks for if the query parameter was set. What do you mean that they cannot be passed to the function. 


Sent from Outlook Mobile



From: tenorz007

Sent: Saturday, March 5, 5:24 PM

Subject: Re: [FCE] Feature url query search (#71)

To: BrainMaestro/FCE

Cc: BrainMaestro



Checks in the controller for what, cause I even noticed all those parameters you put cannot even be passed to the function.

**Comment by tenorz007** [comment]
You don't need to check anything in the controller, I don't know if you
went through the code.

**Comment by BrainMaestro** [comment]
Wouldn't you have to check if the query parameter was set and then pass null if not? Besides however you do it you'll still duplicate something across all the methods that need to search


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 8:43 AM -0800, "tenorz007" <notifications@github.com> wrote:





You don't need to check anything in the controller, I don't know if you
went through the code.
On Mar 5, 2016 17:33, "BrainMaestro" <notifications@github.com> wrote:

>
>
> Checks for if the query parameter was set. What do you mean that they
> cannot be passed to the function.
>
>
> Sent from Outlook Mobile
>
>
>
> From: tenorz007
>
> Sent: Saturday, March 5, 5:24 PM
>
> Subject: Re: [FCE] Feature url query search (#71)
>
> To: BrainMaestro/FCE
>
> Cc: BrainMaestro
>
>
>
> Checks in the controller for what, cause I even noticed all those
> parameters you put cannot even be passed to the function.
>
>
> —
>
> Reply to this email directly or view it on GitHub.
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrainMaestro/FCE/pull/71#issuecomment-192681568>.
>


---

**Comment by tenorz007** [comment]
It looks better now, I had considered doing that before... This way it is neater

**Comment by BrainMaestro** [comment]
Okay this is better. Why are there many `Rebase` commits though. In fact the commit history is rather messy. I'll make some minor changes and merge it.

**Comment by BrainMaestro** [comment]
What happened to the tests?

**Comment by tenorz007** [comment]
What test, test to the all method tests it too, also from the route test. Besides, testing that specifically would involve mocking and I don't know how you'd do that given that's an abstract class. I don't see you testing the limit or page either.....

**Comment by BrainMaestro** [comment]
You have to agree that limit and page are very minor compared to this. Why would the test involve mocking? There's no external dependency to mock. 

You can pick one of the repositories and test it from there. Preferably something that has a lot of fields like `Semester`

**Comment by tenorz007** [comment]
Test it how, did you look at the code for it. It gets the query using the Input Façade and it defaults to null, so how do you want to change that without mocking it. Nope they aren’t minor.

**Comment by BrainMaestro** [comment]
You didn't even try to test it, if not you would have found a way. I used the Input façade in my UserController test. Go and look at it. 

If you want me to merge this
- squash this thing into one commit.
- add tests as a new commit.

**Comment by tenorz007** [comment]
I didn't try to test it really, didn't I write it before I converted it to
how it is. And I did test it. You can squash it if you want.

You didn't even try to test it, if not you would have found a way. I used
the Input façade in my UserController test. Go and look at it.

If you want me to merge this

   - squash this thing into one commit.
   - add tests as a new commit.

—
Reply to this email directly or view it on GitHub
<https://github.com/BrainMaestro/FCE/pull/71#issuecomment-192973445>.

**Comment by BrainMaestro** [comment]
Approved. I'm not going to squash your commits next time.

**Pull request merged**
