### PR TITLE
Refactored the findby method to to be more concise

### PR DESCRIPTION
**Pull request by BrainMaestro**
Parameters $field and $value where combined into an associative array $params

### CODE REVIEW

**Comment by tenorz007** [comment]
Is the styling correct findBy([
], 'all');?

**Comment by BrainMaestro** [comment]
There doesn't seem to be anything against it in psr2. The IDE doesn't complain. It doesn't look very good on a separate line. Try it out and check.

**Comment by BrainMaestro** [comment]
LGTM

**Comment by tenorz007** [comment]
LGTM

**Pull request merged**
