### PR TITLE
Directly increment column value

### PR DESCRIPTION
**Pull request by BrainMaestro**
Also removed update method hack

### CODE REVIEW

**Comment by tenorz007** [comment]
There is an eloquent increment.

**Comment by tenorz007** [comment]
Good job finding this. LGTM

**Comment by BrainMaestro** [comment]
Yeah thanks. LGTM

**Comment by BrainMaestro** [comment]
Yeah thanks. LGTM


Sent from Outlook Mobile






On Sun, Feb 21, 2016 at 11:04 AM -0800, "tenorz007" <notifications@github.com> wrote:





Good job finding this. LGTM

---

**Comment by tenorz007** [comment]
build failed

**Comment by BrainMaestro** [comment]
Failing build will be fixed after merging #35 and rebasing

**Comment by BrainMaestro** [comment]
Approved!

**Pull request merged**
