### PR TITLE
Add full repository functionality

### LINKED ISSUE #30: Repositories
- [x] Base Repository class
- [x] Repository interfaces (contracts)
- [x] Implementation of repository interfaces with eloquent 
      - [x] Evaluation
      - [x] Section
      - [x] User
      - [x] School
      - [x] Semester
      - [x] Key
      - [x] Question
      - [x] QuestionSet
      - [x] Semester and QuestionSet related functions

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #30.
@SkaeX @tenorz007. Let's give this one more look

### CODE REVIEW

**Comment by SkaeX** [comment]
Why does a `Comment` belongTo a `QuestionSet`?

**Comment by BrainMaestro** [comment]
It belongs to both a `QuestionSet` and `Semester`. The relationship only matters from the `Comment` perspective. It's basically useless for the `QuestionSet` because we will never retrieve them that way.

**Comment by SkaeX** [comment]
:+1: Thanks!

**Comment by BrainMaestro** [comment]
Whoops! This was a mistake

**Pull request merged**
