### PR TITLE
Added test for fail path of createKeys

### PR DESCRIPTION
**Pull request by BrainMaestro**
Finally. :smile:

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Approved

**Comment by tenorz007** [comment]
I was going to ask about this...

**Comment by BrainMaestro** [comment]
Yeah. Was looking for a better way to test it, but this'll do for now. Let me assign this to you since @SkaeX is a bit busy now

**Comment by tenorz007** [comment]
Approved

**Pull request merged**
