### PR TITLE
Add view users

### PR DESCRIPTION
**Pull request by SkaeX**

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Maybe we should add their roles as well

**Comment by SkaeX** [comment]
I don't know if it is just me or my postman, but I did not see roles.

**Comment by BrainMaestro** [comment]
You need to include them.





On Thu, Jun 2, 2016 at 10:38 AM -0700, "SkaeX" <notifications@github.com> wrote:





I don't know if it is just me or my postman, but I did not see roles.

---

**Comment by BrainMaestro** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/BrainMaestro/FCE/pull-request/168/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=BrainMaestro/FCE)

**Pull request merged**
